version: 2
updates:

# Maintain dependencies for docker
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
  - "volker-raschek"
  labels:
  - "dependabot"
  - "dependabot/docker"

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
  - "volker-raschek"
  labels:
  - "dependabot"
  - "dependabot/github-actions"

# Maintain dependencies for golang
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
  - "volker-raschek"
  labels:
  - "dependabot"
  - "dependabot/gomod"
