name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    permissions:
      actions: read
      checks: read
      contents: write
      statuses: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: minor
        github-token: ${{ secrets.GITHUB_TOKEN }}